### ISSUE TITLE
[Admin] Add the ability to login as admin.

### ISSUE THREAD

**Issue by mohammedri** [uwblueprint/help-lesotho#6]
This will require you to add a new column in the users database that will indicate whether user is admin.

**Comment by gautamgupta** [comment]
@rysharm I remember you showing me this is done. Can you comment on its progress?

**Comment by rysharm** [comment]
@GautamGupta yes we added an admin boolean field to the database but currently the only functionality of logging in as an admin is the ability to delete other users posts and comments

**Comment by gautamgupta** [comment]
@rysharm Let's track other tasks in other tickets. :)
