### ISSUE TITLE
[Admin] Add functionality to delete any posts.

### ISSUE THREAD

**Issue by mohammedri** [uwblueprint/help-lesotho#7]
The admin should have the ability to delete any posts he/she considers to be offensive/discriminatory.

**Comment by rperryng** [comment]
What does this include?  deletion of a post by the user who made it?  Deletion of arbitrary posts by any admins?

**Comment by mohammedri** [comment]
@rperryng Deletion of arbitrary posts by admins

**Comment by rperryng** [comment]
Finished in #12
